---
title: An R Markdown document converted from "./permutation-tests-wits.ipynb"
output: html_document
---

### Loading the dataset containing the export data alongside with the nodal attribute available on each country

```{r}
edges = read.csv('../datasets/wits/simulated/edgelist.csv')
nodes = read.csv('../datasets/wits/simulated/nodelist.csv')
```

```{r}
n = dim(nodes)[1]
N = 1000
country_names = nodes$country_iso3
nodes = transform(nodes, landlocked=as.logical(landlocked))
nodes = subset(nodes, select = -c(population, area, gdp_per_capita))
```

### Importing the library required for doing permutation tests

```{r}
library(coin)
library(sna)
library(ergm)
library(dplyr)
```

```{r}
head(nodes, 3)
```

```{r}
head(edges, 3)
```

### Examining the effect of homophily on the network of trades

```{r}
count_homophily = function(edges, nodes, attrs, ...) {
    count = 0
    for (i in 1:dim(edges)[1]) {
        if (attrs[nodes$country_iso3 == edges$source[i]] == attrs[nodes$country_iso3 == edges$target[i]]) {
            count = count + 1
        }
    }
    return(count)
}
```

```{r}
execute_permutation_test = function(edges, nodes, func, attrs, attr, ...) {
    params = list(...)
    observed_statistic = func(edges, nodes, attrs, params)

    
#     generating new samples by permutating the attributes
    permutated_samples = matrix(0, nrow = n, ncol = N)
    for (i in 1:N) {
        permutated_samples[, i] = sample(x = attrs, size = n, replace = F)
    }
    
#    computing the specified statistic for all the permutated networks
    permutated_statistics = matrix(0, nrow = N, ncol = 1)
    for (j in 1:N) {
        permutated_statistics[j] = func(edges, nodes, permutated_samples[, j], params)
    }
    
    p_value = mean(permutated_statistics < observed_statistic)
    if (p_value > .5) {
        p_value = 1 - p_value
    }
    
    print(paste(attr, ',', p_value))
    pdf(paste('../results/', attr, '.pdf'))
    par(bg = 'white')
    hist(
        permutated_statistics, 
        xlim=c(min(min(permutated_statistics), observed_statistic), max(max(permutated_statistics), observed_statistic)), 
        main = paste('Comparison of the observed statistic and \npermutated ones with respect to \n', attr, 'with p-value: ', p_value)
    )
    abline(v=observed_statistic, col='red')
    
    dev.off()
    return(data.frame(
        effect = attr, 
        p_value = p_value
    ))
}
```

```{r}
categories = !unlist(lapply(nodes, FUN = is.numeric))
categories[attr(categories, 'names') == 'country_iso3'] = FALSE
categories = colnames(nodes[, categories])
```

```{r}
homophily_results = data.frame()
for (col in categories) {
    homophily_results = homophily_results %>%
        dplyr::bind_rows(
            execute_permutation_test(
                edges,
                nodes,
                count_homophily,
                nodes[, col],
                paste('homophily-', as.character(col), sep = '')
            )
        )
}
```

### Examining the effect of higher values for nodal covariates

```{r}
compute_nodecov = function(edges, nodes, attrs, ...) {
    attrs = attrs - mean(attrs)
#     log transformation parameter
    params = list(...)
    sum = 0
    for (i in 1:dim(edges)[1]) {
        if (as.logical(params[[1]])) {
            sum = sum + log(attrs[nodes$country_iso3 == edges$source[i]] + attrs[nodes$country_iso3 == edges$target[i]])
        } else {
            sum = sum + attrs[nodes$country_iso3 == edges$source[i]] + attrs[nodes$country_iso3 == edges$target[i]]
        }
    }
    return(sum)
}
```

```{r}
compute_absdiff = function(edges, nodes, attrs, ...) {
    attrs = attrs - mean(attrs)
#     log transformation parameter
    params = list(...)
    diff_sum = 0
    for (i in 1:dim(edges)[1]) {
        if (as.logical(params[[1]])) {
            diff_sum = diff_sum + log(1 + abs(attrs[nodes$country_iso3 == edges$source[i]] - attrs[nodes$country_iso3 == edges$target[i]]))
        } else {
            diff_sum = diff_sum + abs(attrs[nodes$country_iso3 == edges$source[i]] - attrs[nodes$country_iso3 == edges$target[i]])
        }
    }
    return(diff_sum)
}
```

```{r}
nums <- unlist(lapply(nodes, is.numeric))
nums = colnames(nodes[, nums])
```

```{r}
nodecov_results = data.frame()
absdiff_results = data.frame()
for (col in nums) {
    nodecov_results = nodecov_results %>%
        dplyr::bind_rows(
            execute_permutation_test(
                edges,
                nodes,
                compute_nodecov,
                nodes[, col],
                paste('nodecov-', as.character(col), sep = ''), 
                FALSE
            )
        )
    absdiff_results = absdiff_results %>%
        dplyr::bind_rows(
            execute_permutation_test(
                edges,
                nodes,
                compute_absdiff,
                nodes[, col],
                paste('absdiff-', as.character(col), sep = ''), 
                FALSE
            )
        )
}
```

### Transform numerical data to categorical and do homophily test

```{r}
numerical_homophily = function(edges, nodes, attrs, ...) {
    m = .5 * length(edges)
    attrs = attrs - mean(attrs)
    result = 0
    for (i in 1:dim(edges)[1]) {
        result = result + attrs[which(nodes$country_iso3 == edges$source[i])] * attrs[which(nodes$country_iso3 == edges$target[i])]
    }
    result = result / 2 / m / sum(attrs**2) * n
    return(result)
}
```

```{r}
numerical_homophily_results = data.frame()
for (col in nums) {
    numerical_homophily_results = numerical_homophily_results %>% 
        dplyr::bind_rows(
            execute_permutation_test(
                edges,
                nodes,
                numerical_homophily, 
                nodes[, col],
                paste('numerical-homophily-', as.character(col), sep = '')
            )
        )
}
```

```{r}
all_results = rbind(
    nodecov_results, 
    absdiff_results, 
    homophily_results, 
    numerical_homophily_results
)
```

```{r}
write.csv(all_results, '../results/general_permutation_tests.csv', row.names=F)
```

